### ISSUE TITLE
Updated entries

### ISSUE THREAD

**Issue by tkittel** [afedynitch/x4i3#1]
Hi there,

Thanks for making this highly useful interface available! I was wondering if there are any plans to create an updated release with the latest EXFOR entries from the last few years? Or is there a way I missed for forcing my local installation to update to the latest EXFOR files?

Cheers,
Thomas

**Comment by afedynitch** [comment]
Hi Thomas,
yes, this is definitely possible. I will look into this issue. The most recent update is from March 08 2021. I'll try to work this in.

**Comment by afedynitch** [comment]
The database has been updated to that dated 2021-03-08. Please update to 1.2.0 via pip, or by pulling the release or master.

Enjoy.

**Comment by tkittel** [comment]
Fantastic, thanks a lot!!
