### ISSUE TITLE
'X4CrossSectionDataSet' object has no attribute 'meta'

### ISSUE THREAD

**Issue by avoyles** [afedynitch/x4i3#7]
First off, this package has been GREAT!!! Thanks so much for the update to Python 3 - though the auto-docs still point to the old python2 docs for x4i.

Anyways - see the title.  When pulling up a subentry (in this case, for `x4EntryFactory('D0576', 'D0576011', ' ')`, not all of the attributes listed in the `exfor_dataset.py` source appear to be returnable.  Of the attributes `meta, common, reaction, monitor, data, pointer`, only `data`, `monitor`, and `reaction` seem to be returnable.

I might be missing a more clever way, as I'm accessing datasets via iteration over `db.retrieve()` currently:

```
x = db.retrieve(target='BI-209',reaction='D,2N',quantity='SIG' )
for key in x.keys():
	entry = x[key]
	datasets = entry.getDataSets()
	for i in datasets.values():
		print(i.getSimplified())
		print(i.getSimplified().data)
```

I'm working on using string methods to pull the relevant metadata attributes from a dataset, but is there an in-built way to do this already?   Thanks!

**Comment by avoyles** [comment]
FYI - string methods work well as a workaround, at least:  for a given `x4i3.exfor_dataset.X4CrossSectionDataSet` object "`subentry`":

```
split_str = str(subentry).split('Authors:',1)[1].split('Title:',1)
author_name = split_str[0].strip().split(',', 1)[0].split('.',-1)[-1]
year = split_str[1].strip().split('Year:',1)[1].strip().split('\n',1)[0]
```

etc etc

**Comment by afedynitch** [comment]
Hi! Great this package is useful for you.

I'm wondering why you don't access the metadata directly from the subentry attributes, e.g.:
```
x = db.retrieve(target='BI-209',reaction='D,2N',quantity='SIG' )
for key in x.keys():
	entry = x[key]
	datasets = entry.getDataSets()
	for i in datasets.values():
		# print(i.getSimplified())
		# print(i.getSimplified().data)
                    print(i.author)
                    print(i.year)
                    break

>> ['W.J.Ramler', 'J.Wing', 'D.J.Henderson', 'J.R.Huizenga']
>> 1959
```

**Comment by avoyles** [comment]
See, this is why I figured I'd check!  That makes far more sense, and is WAY cleaner - thanks!!  I hadn't seen any getter methods for the class, and didn't even think about trying these, to be honest.   

I think a "quick start" guide or a set of various examples (beyond the fission yield data in the README) would be really helpful, especially until documentation is made available, as some of the methods of interacting with the outputs and data structures are not terribly intuitive (but I'm also not fantastic with python in the first place either!).  The auto-doc from Dave's original x4i repo help somewhat, but so much of the source code has changed that many methods don't seem to translate well - for example, many of the examples in his x4i.pdf guide don't work with x4i3, even when copying them exactly - the root differences seem to be differences in how X4Entry vs X4EntryFactory are used, as well as even the input data types they expect.


Again, these are minor issues, and an updated user's guide I think would easily resolve them, at least by showing intended examples of teh architecture.  Thanks again for your work with this!!!  I'll continue to play around and contribute!
